### PR TITLE
I have added order message variable in Bigcommerce to wombat integration...

### PR DESCRIPTION
**Pull request by sheheryarakhan**
... now I have added the same variable so we can transfer the order message from wombat to fifth gear.

### CODE REVIEW

**Comment by phstc** [comment]
@sheheryarakhan where are you setting the variable `order_message`? shouldn't it be `object_payload[:order_message]`? Did you have a chance to test it locally?

Could you also have a look at this comment: https://github.com/wombat/bigcommerce_integration/pull/1#discussion_r26816117

**Comment by sheheryarakhan** [comment]
Please review and merge

**Comment by phstc** [comment]
> Could you also have a look at this comment: https://github.com/wombat/bigcommerce_integration/pull/1#discussion_r26816117

Before merging it, could you also fix the item above and send it along with this PR?

It's adding `order_message` inside `totals` and it should be outside it.

**Comment by phstc** [comment]
> send it along with this PR?

nvm I forgot it was in a different repo.

**Comment by sheheryarakhan** [comment]
Just merge order message so we can get it from wombat to fifth gear

**Comment by sheheryarakhan** [comment]
Thanks please also let me know if you have deployed it.? on wombat so my client can use it

**Comment by phstc** [comment]
Merged & Deployed! 

I've also fixed BigCommerce.

**Comment by sheheryarakhan** [comment]
Hi thanks but I am not able to see order message to send from wombat to fifth gear but I can see its coming from Bigcommerce to Wombat. Please review below are the links 

https://my.wombat.co/accounts/54d1569f776f6d692c9a0000/objects/shipments/Q5OB7C9-300003-S?edit_payload_mode=true

https://my.wombat.co/accounts/54d1569f776f6d692c9a0000/objects/orders/Q5OB7C9-300003?edit_payload_mode=true

**Comment by phstc** [comment]
Please send these questions to support@spreecommerce.com. Specially when they have customer links.

**Comment by sheheryarakhan** [comment]
Hi I am still not able to see order_message in fifthgear

**Comment by sheheryarakhan** [comment]
Can you please let me know why ordermessage is not appearing there ?

**Comment by phstc** [comment]
Could you follow your customer specific questions to support@spreecommerce.com?

**Pull request merged**
